safe: true
lsi: false
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false


last_stjs_version: 3.3.0

defaults:
  -
    scope:
      path: "User_guide"
      type: pages

    values:
      isUserGuide: true # allows quick extraction from site.pages
      layout: userguide